name: main

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: generate-snake-game-from-github-contribution-grid
        uses: Platane/snk@v3.2.0
        env:
          github.repository_owner: ${{ secrets.REPOSITORY_OWNER }}
